### ISSUE TITLE
Availability Update

### ISSUE THREAD

**Issue by grahul27** [grahul27/scheduling-app-client#1]
### To-do Tasks
- [x] Hub clinician should not be able to update Time Slots which are not available any more during the day.
- [x] Show Time Slots in Generated Time Slots for Hub Clinician that are only valid during the day
- [x] Update new page loading for all the web pages in Hub, Spoke and Admin 
- [x] SignIn form Input validation error message
- [x]  Fix update availability ---> when new slots are added and updated, all the slots are going to available
